# Generated by Django 5.0.1 on 2024-02-21 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('img1', models.URLField(max_length=2000)),
                ('price', models.IntegerField()),
            ],
        ),
    ]
