# Generated by Django 4.2.1 on 2024-02-22 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3_auth', '0003_alter_items_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='items',
            name='num',
            field=models.IntegerField(default=True),
        ),
    ]
