# Generated by Django 4.2.1 on 2024-02-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3_auth', '0004_items_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
