# Generated by Django 5.0.1 on 2024-02-25 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web3_auth', '0005_alter_items_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='items',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
